--- #YAML:1.0
name:                Tree-AVL
version:             1.06
abstract:            An AVL (balanced binary) tree for time-efficient storage and retrieval of comparable objects 
license:             ~
author:              
    - Matthias Beebe <matthiasbeebe@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
